sudo: required
services:
  - docker
before_install:
  - docker build -t gmahe/stuart -f ./Dockerfile.dev ./
script:
  - docker run -e CI=true gmahe/stuart npm run test
after_success:
  - docker build -t gmahe/stuart ./
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push to dockerhub
  - docker push gmahe/stuart
## AWS deployment
# deploy:
#   provider:
#   region:
#   app:
#   env:
#   bucket_name:
#   bucket_path:
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
