version: "3"
services:
  # TODO: Add MongoDb
  # mongodb:
  #     image: "mongodb:latest"
  #     environment:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - MONGO_URI_STUART=$MONGO_URI_STUART
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - MONGO_URI_STUART=$MONGO_URI_STUART
    command: npm run test
